services:
  postgres:
    image: 'postgres:latest'
    shm_size: 1g
    hostname: postgres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1.5GB'
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - '5432:5432'
    networks:
      - default

#  api1: # API - Instância 01
#    image: rinha-java21-ccs1201:0.0.1
#    hostname: api1
#    depends_on:
#      - postgres
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: '1.5GB'
#    ports:
#      - '9999:8080'
#    networks:
#      - default

networks:
  default:
#    driver: virtual
#    name: rinha-network